### ISSUE TITLE
New ImageView bounds checking introduces build failures in client software

### ISSUE THREAD

**Issue by Pointedstick** [zxing-cpp/zxing-cpp#708]
Unfortunately that commit is causing KDE software that uses the library (Prison, Spectacle) to fail to build:

```
In file included from /home/nate/kde/usr6/include/ZXing/ReadBarcode.h:9,
                 from /home/nate/kde/src/prison/src/scanner/videoscannerworker.cpp:17:
/home/nate/kde/usr6/include/ZXing/ImageView.h: In constructor ‘ZXing::ImageView::ImageView(const uint8_t*, int, int, ZXing::ImageFormat, int, int)’:
/home/nate/kde/usr6/include/ZXing/ImageView.h:80:105: error: exception handling disabled, use ‘-fexceptions’ to enable
   80 |                         throw std::invalid_argument("Can not construct an ImageView from a NULL pointer");
      |                                                                                                         ^
```

Reverting the commit fixes the issue.

**Comment by axxel** [comment]
That is surprising to me: I can see how that inline function would cause this error if you build your client code with disabled exceptions *but* `zxing-cpp` uses exceptions to communicate error conditions and has always done so. So linking against it with disabled exceptions in the client code would likely cause an abort of the process in case one was thrown? (I have no idea what happens in general in that case).

So you are saying KDE does generally not use / forbid the use of c++ exceptions?!? (@vkrause)

**Comment by axxel** [comment]
Could you easily test if a change like this would fix your build?
```c++
#if __cpp_exceptions
    // new code that throws
#endif
```

**Comment by vkrause** [comment]
> So you are saying KDE does generally not use / forbid the use of c++ exceptions?!? (@vkrause)

We usually have exceptions off by default and only enabled in code actually using/needing them, which is for example some of the code interfacing with ZXing. 

The places where Nate ran into this weren't part of this so far, so that's where this broke now. This also means this can be fixed fairly easily on our side going forward, but things might get a bit messy for distributors combining a newer ZXing release with older releases of our code then (quite possible if this will end up in a near-term patch-level release for example).

**Comment by axxel** [comment]
Interesting. If the above mentioned `__cpp_exceptions` workaround works for this situation, then I'd be happy to include that to make sure the code still keeps compiling.

That said: maybe having at least one `throw` in a public header of `zxing-cpp` is actually a good thing here, because it lets the compiler tell the user that he'd better enables exceptions on the client side to prevent a crash or undefined behavior or what ever is supposed to happen in that case?

**Comment by axxel** [comment]
Looking at the changed made on the KDE side it seems:
1. KDE is/was "[live at head](https://www.youtube.com/watch?v=tISy7EJQPzI)" with regards to this project? Kind of nice from my perspective as a maintainer ;).
2. KDE now is dependent on an external installation of `zxing-cpp`.
3. The translation unit calling into `zxing-cpp` is now compiled with exception handling enabled.
4. @vkrause believes that the used API is not (ever) throwing exceptions, meaning there is no need to have any try/catch involved in KDE code. That is not true and has never been so.
5. There seems to be no interest in the suggested `#if  __cpp_expections` change inside zxing-cpp to prevent the compile error for people trying to compile older KDE code with newer zxing-cpp versions.

Regarding point 4: The `ImageView` constructor implicitly called [here](https://invent.kde.org/frameworks/prison/-/blob/master/src/scanner/videoscannerworker.cpp#L46) may now `throw` if `frame.width()` or `frame.height()` be `<= 0`. But even before the discussed change, there could/would have been exceptions coming from `ReadBarcode()` possible. That said, if there never has been any the way KDE uses this function, the discussed changes did not change that.

**Comment by vkrause** [comment]
> Looking at the changed made on the KDE side it seems:
> 
>     1. KDE is/was "[live at head](https://www.youtube.com/watch?v=tISy7EJQPzI)" with regards to this project? Kind of nice from my perspective as a maintainer ;).
>
>     2. KDE now is dependent on an external installation of `zxing-cpp`.

We still have CI/CD builds using latest master, which helps to catch such issues early. That was however also done in one place where this hit way too many people. That's why this ended up creating various bug reports and complains rather than work on addressing the issue. That has been changed.
 
>     3. The translation unit calling into `zxing-cpp` is now compiled with exception handling enabled.

Right, and which in my understanding is the technically more correct and cleaner solution than (5), and also avoids this problem reoccurring in the future.

>     4. @vkrause believes that the used API is not (ever) throwing exceptions, meaning there is no need to have any try/catch involved in KDE code. That is not true and has never been so.

I might be wrong of course, but the API used there does not seem to throw under the conditions in which we use it (e.g. Qt will not give us negative image/video frame sizes). In places where exceptions actually happen we do handle them.

>     5. There seems to be no interest in the suggested `#if  __cpp_expections` change inside zxing-cpp to prevent the compile error for people trying to compile older KDE code with newer zxing-cpp versions.

That issue remains, at least in parts, but it hasn't been as urgent as unblocking people hit by build issues, therefore I focused on the other measures first. From the two affected places one is new code that has not been released yet, so there we have no problem at all. The other one has a fairly rapid release cycle (monthly), so depending on when the next ZXing release is planned containing this change we might also be able to largely avoid the problem. If this change is likely to hit a release in the very near future I'd still like to explore that workaround though.

> Regarding point 4: The `ImageView` constructor implicitly called [here](https://invent.kde.org/frameworks/prison/-/blob/master/src/scanner/videoscannerworker.cpp#L46) may now `throw` if `frame.width()` or `frame.height()` be `<= 0`. But even before the discussed change, there could/would have been exceptions coming from `ReadBarcode()` possible. That said, if there never has been any the way KDE uses this function, the discussed changes did not change that.

Right, the problem isn't new exception being thrown now, merely that the compiler now sees that this can happen and thus insists on exception handling being enabled.

**Comment by axxel** [comment]
> We still have CI/CD builds using latest master, which helps to catch such issues early. [...] That has been changed.

So you still have some CI-build pull HEAD and can therefore report issues early? I'd appreciate that quite a bit.

> Right, and which in my understanding is the technically more correct and cleaner solution than (5), and also avoids this problem reoccurring in the future.

Absolutely.


> I might be wrong of course, but the API used there does not seem to throw under the conditions in which we use it (e.g. Qt will not give us negative image/video frame sizes). In places where exceptions actually happen we do handle them.

I came to the same conclusion, it is just that technically your statement that the API you use does not throw, was wrong. E.g. if you put in an image where width or height is `>65535` it would also throw (and did so for I don't know how long). And it might be that those are actually the only conditions where `ReadBarcode` throws. The writer part is riddled with `throw std::invalid_agument()`, though.

> That issue remains, at least in parts, but it hasn't been as urgent as unblocking people hit by build issues, therefore I focused on the other measures first. From the two affected places one is new code that has not been released yet, so there we have no problem at all. The other one has a fairly rapid release cycle (monthly), so depending on when the next ZXing release is planned containing this change we might also be able to largely avoid the problem. If this change is likely to hit a release in the very near future I'd still like to explore that workaround though.

I don't see a release "in the very near future". All the work I recently did went into the Rust and .NET wrapper and they are released on their own cycle for now, just so people can get the code into their hands easily and then maybe report back issues they find. So I'll wait and see how things evolve regarding this very issue here.

**Comment by vkrause** [comment]
> So you still have some CI-build pull HEAD and can therefore report issues early? I'd appreciate that quite a bit.

I thought we do, after double-checking it turned out to be no longer the case, so I fixed that. The KDE Itinerary continuous Flatpak build uses latest ZXing again now, as it does for other important external dependencies. That doesn't give us complete coverage of everything we do with ZXing, but it should catch the most impactful issues at least.

> I came to the same conclusion, it is just that technically your statement that the API you use does not throw, was wrong. E.g. if you put in an image where width or height is `>65535` it would also throw (and did so for I don't know how long). And it might be that those are actually the only conditions where `ReadBarcode` throws. The writer part is riddled with `throw std::invalid_agument()`, though.

Right. We do have exception handling for the writer code, and it probably doesn't hurt to harden the reader side as well just to be sure.

> I don't see a release "in the very near future". All the work I recently did went into the Rust and .NET wrapper and they are released on their own cycle for now, just so people can get the code into their hands easily and then maybe report back issues they find. So I'll wait and see how things evolve regarding this very issue here.

Then we should be fine, the fixes on our side have been backported to all relevant branches, so the problem should resolve itself over the next couple of weeks. It's still theoretically possible to mix a future ZXing release with an outdated release of our stuff then, but Linux distributions are extremely unlikely to do something like that (and that's about the only case where this would have a bigger impact).

**Comment by Pointedstick** [comment]
Thanks a lot for the professional-quality follow-up here, folks!

**Comment by axxel** [comment]
Anything more to add here? Otherwise I'll close this issue.
