### ISSUE TITLE
MSVC build is broken, no countl_zero and popcount

### ISSUE THREAD

**Issue by EchterAgo** [zxing-cpp/zxing-cpp#612]
With Visual Studio 2022 I get these errors when building zxing-cpp 2.1.0:

```
  zxing-cpp\core\src\BitHacks.h(41,14): error C2039: 'countl_zero': is not a member of 'std' [zxing-cpp\build\temp.win32-cpython-38\Release\zxingcpp.vcxproj]
  C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.37.32822\include\vector(26,1): message : see declaration of 'std' [zxing-cpp\build\temp.win32-cpython-38\Release\zxingcpp.vcxproj]
  zxing-cpp\core\src\BitHacks.h(84,14): error C2039: 'countr_zero': is not a member of 'std' [zxing-cpp\build\temp.win32-cpython-38\Release\zxingcpp.vcxproj]
  C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.37.32822\include\vector(26,1): message : see declaration of 'std' [zxing-cpp\build\temp.win32-cpython-38\Release\zxingcpp.vcxproj]
  zxing-cpp\core\src\BitHacks.h(153,14): error C2039: 'popcount': is not a member of 'std' [zxing-cpp\build\temp.win32-cpython-38\Release\zxingcpp.vcxproj]
  C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.37.32822\include\vector(26,1): message : see declaration of 'std' [zxing-cpp\build\temp.win32-cpython-38\Release\zxingcpp.vcxproj]
  zxing-cpp\core\src\BitHacks.h(153,14): error C3861: 'popcount': identifier not found [zxing-cpp\build\temp.win32-cpython-38\Release\zxingcpp.vcxproj]
```

This seems to be caused by https://github.com/zxing-cpp/zxing-cpp/commit/9980b2da410c4194578d942cd1d6d4d619a05722 and building version 2.0.0 works.

**Comment by axxel** [comment]
Hallo Axel (du bist erst der 3. andere Axel der mir in meinem Leben über den Weg lief ;)).

1) Since PyPi has pre-build binary packages for windows available, why would you need to build them yourself?
2) Why would MSVC define the macro `__cpp_lib_bitops` and then not provide the functions that are supposed to be there iff this macro is defined? Could it be that your environment defines the macro `__ANDROID__` somewhere? (See the patch you linked above).

**Comment by EchterAgo** [comment]
Axels gibt es zu wenige, ich kenne auch nicht mehr :) Viele denken es wäre Alex aber falsch geschrieben.

1. The project I'm adding zxing-cpp to prefers building from source when possible, but I'm also working on https://github.com/zxing-cpp/zxing-cpp/issues/283 based on the code you posted there. I'll post an update in that issue once I'm ready.
2. I'll investigate whether `__ANDROID__ ` or `__cpp_lib_bitops` is defined. I'm just using `python setup.py install` with VS2022 to install.

**Comment by EchterAgo** [comment]
Ok, so this failure happens only when building the Python wrappers `zxing.cpp` and the failure is because `__cplusplus > 201703L` in `BitHacks.h` is false, which is why `<bit>` is not included.

Building the rest of ZXing actually succeeds, not sure why there would be different values. 

Command line for building the wrapper:

```
C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.37.32822\bin\HostX64\x64\CL.exe /c /I"H:\dev\zxing-cpp\wrappers\python\core\src" /I"H:\dev\zxing-cpp\wrappers\python\build\temp.win-amd64-cpython-310\Release\ZXing" /nologo /W1 /WX- /diagnostics:column /MP /O2 /Ob2 /GL /D _WINDLL /D _MBCS /D WIN32 /D _WINDOWS /D NDEBUG /D "CMAKE_INTDIR=\"Release\"" /D zxingcpp_EXPORTS /Gm- /EHsc /MD /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /std:c++20 /Fo"zxingcpp.dir\Release\\" /Fd"zxingcpp.dir\Release\vc143.pdb" /external:W0 /Gd /TP /errorReport:queue  /external:I "H:/dev/zxing-cpp/wrappers/python/build/temp.win-amd64-cpython-310/Release/_deps/pybind11-src/include" /external:I "C:/Program Files/WindowsApps/PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0/Include" /bigobj "H:\dev\zxing-cpp\wrappers\python\zxing.cpp"
```

Command line for building the rest of ZXing:

```
C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.37.32822\bin\HostX64\x64\CL.exe /c /I"H:\dev\zxing-cpp\core\src" /I"H:\dev\zxing-cpp\build\core" /Zi /nologo /W1 /WX- /diagnostics:column /Od /Ob0 /D _UNICODE /D UNICODE /D WIN32 /D _WINDOWS /D ZXING_BUILD_READERS /D ZXING_BUILD_WRITERS /D _SCL_SECURE_NO_WARNINGS /D _CRT_SECURE_NO_WARNINGS /D _CRT_NONSTDC_NO_WARNINGS /D NOMINMAX /D UNICODE /D _UNICODE /D "CMAKE_INTDIR=\"Debug\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /std:c++17 /Fo"ZXing.dir\Debug\\" /Fd"H:\dev\zxing-cpp\build\core\Debug\ZXing.pdb" /external:W1 /Gd /TP /errorReport:queue  /Zc:__cplusplus <source files>
```

**Comment by EchterAgo** [comment]
Oh, looks like the wrapper is missing `/Zc:__cplusplus`, I'll look into how to add that.
