### ISSUE TITLE
error C2371 and C2572 with pre-compiled headers on MSVC

### ISSUE THREAD

**Issue by th1722** [zxing-cpp/zxing-cpp#685]
After zxing-cpp v2.2.1, It is impossible to compile libreoffice on Windows because it falls with error:

```
[build CXX] workdir/UnpackedTarball/zxing/core/src/datamatrix/DMReader.cpp
[build CXX] workdir/UnpackedTarball/zxing/core/src/datamatrix/DMSymbolInfo.cpp
C:/sources/libo-core/workdir/UnpackedTarball/zxing/core/src/DecodeHints.cpp(15): error C2371: 'ZXing::DecodeHints': redefinition; different basic types
C:\sources\libo-core\workdir\UnpackedTarball\zxing\core\src\ReaderOptions.h(176): note: see declaration of 'ZXing::DecodeHints'
C:/sources/libo-core/workdir/UnpackedTarball/zxing/core/src/DecodeHints.cpp(20): error C2572: 'ZXing::ReadBarcode': redefinition of default argument: parameter 1
C:\sources\libo-core\workdir\UnpackedTarball\zxing\core\src\ReadBarcode.h(21): note: see declaration of 'ZXing::ReadBarcode'
C:/sources/libo-core/workdir/UnpackedTarball/zxing/core/src/DecodeHints.cpp(25): error C2572: 'ZXing::ReadBarcodes': redefinition of default argument: parameter 1
C:\sources\libo-core\workdir\UnpackedTarball\zxing\core\src\Result.h(37): note: see declaration of 'ZXing::ReadBarcodes'
[build CXX] workdir/UnpackedTarball/zxing/core/src/datamatrix/DMVersion.cpp
[build CXX] workdir/UnpackedTarball/zxing/core/src/datamatrix/DMWriter.cpp
make[1]: *** [C:/sources/libo-core/solenv/gbuild/LinkTarget.mk:410: C:/sources/libo-core/workdir/GenCxxObject/UnpackedTarball/zxing/core/src/DecodeHints.o] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:289: build] Error 2
```

**Comment by th1722** [comment]
> Do you know if the libreoffice scripts are compiling zxing-cpp as static or as dynamic library?

LibreOffice scripts compile zxing-cpp as static library.

> Can you confirm that libreoffice compiles with the 2.2.0 release?

Yes.

**Comment by axxel** [comment]
Thanks for the info. The file `DecodeHints.cpp` is actually not required at all in a static build, so I can patch it such that it gets excluded in this case. That said, I'm reluctant to make yet another release just for this when the trivial solution is to compile libreoffice with 2.2.0. The only addition of 2.2.1 is the addition of the file that breaks your build.

**Comment by ilmari-lauhakangas** [comment]
Thanks, axxel. Yes, the build box was using pre-compiled headers as the log had:

> checking whether to enable pch feature... yes (full)

**Comment by axxel** [comment]
@ilmari-lauhakangas thanks for the confirmation of my suspicion. Is simply going back to 2.2.0 a viable solution for your build issues?

**Comment by ilmari-lauhakangas** [comment]
The unmerged patch is https://gerrit.libreoffice.org/c/core/+/160528

Taichi has a lot of experience in applying additional patches on top of external dependencies, so I suppose your commits from today can be added as a .patch file.

**Comment by axxel** [comment]
Looking at that patch, the most strait forward fix would be to simply use 2.2.0 in https://gerrit.libreoffice.org/c/core/+/160528/4/download.lst . No need for any additional patching in that case. If you insist on using 2.2.1, then the only needed patch would be [this one](https://github.com/zxing-cpp/zxing-cpp/commit/fd456f4bd373e07f88e8102bb1e1f50aacf7c279), I believe. With a static build, you would then simply have 2.2.0.

**Comment by ilmari-lauhakangas** [comment]
But what if Linux packagers want to use zxing from their system and thus would prefer 2.2.1 over 2.2.0, right?

**Comment by axxel** [comment]
> But what if Linux packagers want to use zxing from their system and thus would prefer 2.2.1 over 2.2.0, right?

They can do that just fine. The only point of introducing 2.2.1 was to enable someone with a dynamically linked executable compiled with 2.1.0 (or 2.0.0) to still run with a 2.2.1 so-file (without recompilation).

That said, I just realized that I did not cater the other direction: if you dynamically link against 2.2.x, your executable will not work with a `libZXing.2.1.0.so`. That means your minimum required `zxing-cpp` version is 2.2.0 and packagers will have to take care for that. So if someone wants to have a new LibreOffice, they also need a new zxing-cpp (either 2.2.0 or 2.2.1).

Does that make sense to you?

**Comment by ilmari-lauhakangas** [comment]
It makes sense, thanks.

**Comment by axxel** [comment]
@th1722 I received an email notification for a comment you posted here about "backporting a patch to this repository". But in the web gui of github it does not show up. Did you delete it because it is obsolete or is there a bug in github?

**Comment by axxel** [comment]
Only now did I realize that LibreOffice does not use the cmake build files provided by `zxing-cpp` but rolls it's own (ughh) and that was the "attack vector" for the precompiled headers change.

Anyway, I see that LibreOffice now builds and runs on 2.2.1, so this issue fixed, right?
